pages/urls.py
from django.urls import path

from pages.views import HomeView, ContactView, AboutView, BlogView, DestinationView, LoginView, RegisterView

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('destination/', DestinationView.as_view(), name='destination'),
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register')
]

tour/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls'))
]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('accounts/', include('registration.backends.default.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Travelo</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.css'%}">
    <link rel="stylesheet" href="{% static 'css/slick.css'%}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css'%}">

    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

{% include 'layouts/header.html' %}

{% block content %}{% endblock %}

{% include 'layouts/footer.html' %}


  <!-- Modal -->
  <div class="modal fade custom_search_pop" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="serch_form">
            <input type="text" placeholder="Search" >
            <button type="submit">search</button>
        </div>
      </div>
    </div>
  </div>
    <!-- link that opens popup -->
<!--
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://static.codepen.io/assets/common/s1topExecutionOnTimeout-de7e2ef6bfefd24b79a3f68b414b87b8db5b08439cac3f1012092b2290c719cd.js"></script>

    <script src=" https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"> </script> -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'js/ajax-form.js'%}"></script>
    <script src="{% static 'js/waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{% static 'js/scrollIt.js'%}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/nice-select.min.js'%}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>
    <script src="{% static 'js/gijgo.min.js'%}"></script>
    <script src="{% static 'js/slick.min.js'%}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js'%}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{% static 'js/jquery.form.js'%}"></script>
    <script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/mail-script.js'%}"></script>


    <script src="{% static 'js/main.js'%}"></script>
    <script>
        $('#datepicker').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
             rightIcon: '<span class="fa fa-caret-down"></span>'
         }
        });
    </script>
</body>

</html>

templates/layouts/footer.html
{% load static %}
<footer class="footer">
    <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-xl-4 col-md-6 col-lg-4 ">
                    <div class="footer_widget">
                        <div class="footer_logo">
                            <a href="#">
                                <img src="img/footer_logo.png" alt="">
                            </a>
                        </div>
                        <p>5th flora, 700/D kings road, green <br> lane New York-1782 <br>
                            <a href="#">+10 367 826 2567</a> <br>
                            <a href="#">contact@carpenter.com</a>
                        </p>
                        <div class="socail_links">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="ti-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="ti-twitter-alt"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-pinterest"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-youtube-play"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-xl-2 col-md-6 col-lg-2">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Company
                        </h3>
                        <ul class="links">
                            <li><a href="#">Pricing</a></li>
                            <li><a href="#">About</a></li>
                            <li><a href="#"> Gallery</a></li>
                            <li><a href="#"> Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Popular destination
                        </h3>
                        <ul class="links double_links">
                            <li><a href="#">Indonesia</a></li>
                            <li><a href="#">America</a></li>
                            <li><a href="#">India</a></li>
                            <li><a href="#">Switzerland</a></li>
                            <li><a href="#">Italy</a></li>
                            <li><a href="#">Canada</a></li>
                            <li><a href="#">Franch</a></li>
                            <li><a href="#">England</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6 col-lg-3">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Instagram
                        </h3>
                        <div class="instagram_feed">
                            <div class="single_insta">
                                <a href="#">
                                    <img src="img/instagram/1.png" alt="">
                                </a>
                            </div>
                            <div class="single_insta">
                                <a href="#">
                                    <img src="img/instagram/2.png" alt="">
                                </a>
                            </div>
                            <div class="single_insta">
                                <a href="#">
                                    <img src="img/instagram/3.png" alt="">
                                </a>
                            </div>
                            <div class="single_insta">
                                <a href="#">
                                    <img src="img/instagram/4.png" alt="">
                                </a>
                            </div>
                            <div class="single_insta">
                                <a href="#">
                                    <img src="img/instagram/5.png" alt="">
                                </a>
                            </div>
                            <div class="single_insta">
                                <a href="#">
                                    <img src="img/instagram/6.png" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copy-right_text">
        <div class="container">
            <div class="footer_border"></div>
            <div class="row">
                <div class="col-xl-12">
                    <p class="copy_right text-center">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                        All rights reserved | This template is made with <i class="fa fa-heart-o"
                                                                            aria-hidden="true"></i> by <a
                            href="https://colorlib.com" target="_blank">Colorlib</a>.Downloaded from <a
                            href="https://themeslab.org/" target="_blank">Themeslab</a>

                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/layouts/header.html
{% load static %}
{% load i18n %}
<header>
    <div class="header-area ">
        <div id="sticky-header" class="main-header-area">
            <div class="container-fluid">
                <div class="header_bottom_border">
                    <div class="row align-items-center">
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo">
                                <a href="index.html">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul>
                                        <li class="{% if request.path == '/' %}active{% endif %}">
                                            <a href="{% url 'pages:home' %}">{% trans 'Home' %}</a>
                                        </li>
                                        <li class="{% if request.path == '/about/' %}active{% endif %}">
                                            <a href="{% url 'pages:about' %}">{% trans 'About' %}</a>
                                        </li>
                                        <li class="{% if request.path == '/contact/' %}active{% endif %}">
                                            <a href="{% url 'pages:contact' %}">{% trans 'Contacts' %}</a>
                                        </li>
                                        <li class="{% if request.path == '/blog/' %}active{% endif %}">
                                            <a href="{% url 'pages:blog' %}">{% trans 'Blog' %}</a>
                                        </li>
                                        <li class="{% if request.path == '/destination/' %}active{% endif %}">
                                            <a href="{% url 'pages:destination' %}">{% trans 'Destination' %}</a>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 d-none d-lg-block">
                            <div class="social_wrap d-flex align-items-center justify-content-end">
                                <div class="number">
                                    <p><i class="fa fa-phone"></i> 10(256)-928 256</p>
                                </div>
                                <div class="social_links d-none d-xl-block">
                                    <ul>
                                        <li><a href="#"> <i class="fa fa-instagram"></i> </a></li>
                                        <li><a href="#"> <i class="fa fa-linkedin"></i> </a></li>
                                        <li><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                                        <li><a href="#"> <i class="fa fa-google-plus"></i> </a></li>
                                        {% if request.user.is_authenticated %}
                                        <li><a href="{% url 'auth_logout' %}">{% trans 'Log out' %}</a></li>
                                        {% else %}
                                        <li><a href="{% url 'auth_login' %}">{% trans 'Sign in' %}</a>
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</header>